/* AuditDesk renderer: local-first financial audit workbench. */
(() => {
  'use strict';

  const bridge = window.auditdesk || null;
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => Array.from(root.querySelectorAll(selector));
  const iconPaths = {
    grid: '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    'grid-tool': '<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/><path d="M7 10v4M17 10v4M10 7h4M10 17h4"/>',
    database: '<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v7c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 12v7c0 1.7 3.6 3 8 3s8-1.3 8-3v-7"/>',
    book: '<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5v-16Z"/><path d="M4 18.5A2.5 2.5 0 0 1 6.5 16H20M8 7h7M8 10h5"/>',
    folder: '<path d="M3 6a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v9a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V6Z"/>',
    settings: '<path d="M12 15.2a3.2 3.2 0 1 0 0-6.4 3.2 3.2 0 0 0 0 6.4Z"/><path d="m19.4 15 .1.1a1.8 1.8 0 1 1-2.5 2.5l-.1-.1a1.8 1.8 0 0 0-3.1 1.3v.2a1.8 1.8 0 1 1-3.6 0v-.2a1.8 1.8 0 0 0-3.1-1.3l-.1.1a1.8 1.8 0 1 1-2.5-2.5l.1-.1A1.8 1.8 0 0 0 3.3 12a1.8 1.8 0 0 0-1.3-3.1h-.2a1.8 1.8 0 1 1 0-3.6H2A1.8 1.8 0 0 0 3.3 2l-.1-.1a1.8 1.8 0 1 1 2.5-2.5l.1.1A1.8 1.8 0 0 0 9 1.8v-.2a1.8 1.8 0 1 1 3.6 0v.2A1.8 1.8 0 0 0 15.7 3l.1-.1a1.8 1.8 0 1 1 2.5 2.5l-.1.1A1.8 1.8 0 0 0 19.5 9h.2a1.8 1.8 0 1 1 0 3.6h-.2a1.8 1.8 0 0 0-.1 2.4Z"/>',
    search: '<circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/>',
    upload: '<path d="M12 16V4M7 9l5-5 5 5M4 20h16"/>',
    save: '<path d="M5 3h12l2 2v16H5z"/><path d="M8 3v6h8V3M8 21v-7h8v7"/>',
    'chevron-right': '<path d="m9 18 6-6-6-6"/>',
    'arrow-left': '<path d="M20 12H4M10 6l-6 6 6 6"/>',
    check: '<path d="m5 12 4 4L19 6"/>',
    'check-circle': '<circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/>',
    alert: '<path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v4M12 17h.01"/>',
    info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/>',
    play: '<path d="m8 5 11 7-11 7V5Z"/>',
    download: '<path d="M12 3v12M7 10l5 5 5-5M4 20h16"/>',
    file: '<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h5"/>',
    plus: '<path d="M12 5v14M5 12h14"/>',
    x: '<path d="m6 6 12 12M18 6 6 18"/>',
    spark: '<path d="m12 2 1.5 6.5L20 10l-6.5 1.5L12 18l-1.5-6.5L4 10l6.5-1.5L12 2Z"/>',
    calculator: '<rect x="5" y="2.5" width="14" height="19" rx="2"/><path d="M8 6h8M8 10h2M14 10h2M8 14h2M14 14h2M8 18h2M14 18h2"/>',
    bank: '<path d="m3 9 9-5 9 5M5 10v7M9 10v7M15 10v7M19 10v7M3 19h18"/>',
    revenue: '<path d="M4 19V5M4 19h17M7 15l3-4 3 2 5-7"/><path d="M15 6h4v4"/>',
    purchase: '<path d="M4 7h16v13H4zM8 7V4h8v3M8 11h8M8 15h5"/>',
    inventory: '<path d="m4 7 8-4 8 4v10l-8 4-8-4V7Z"/><path d="M4 7l8 4 8-4M12 11v10"/>',
    expense: '<path d="M6 3h12v18H6zM9 7h6M9 11h6M9 15h4"/>',
    payroll: '<circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M17 11h4M19 9v4"/>',
    journal: '<path d="M5 4h14v16H5zM8 8h8M8 12h3M8 16h6"/>',
    shield: '<path d="M12 21s8-3.8 8-10V5l-8-3-8 3v6c0 6.2 8 10 8 10Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/>',
    link: '<path d="M10 13.8 8.5 15.3a3.2 3.2 0 0 1-4.5-4.5l3-3a3.2 3.2 0 0 1 4.5 0M14 10.2l1.5-1.5a3.2 3.2 0 0 1 4.5 4.5l-3 3a3.2 3.2 0 0 1-4.5 0M8 16l8-8"/>',
    filter: '<path d="M4 5h16M7 12h10M10 19h4"/>',
    clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    user: '<circle cx="12" cy="8" r="3.5"/><path d="M5 21a7 7 0 0 1 14 0"/>',
    book2: '<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5v-16Z"/><path d="M8 7h7M8 11h5"/>',
    close: '<path d="m6 6 12 12M18 6 6 18"/>'
  };
  function icon(name, className = '') { return `<svg class="${className}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name] || iconPaths.info}</svg>`; }
  function hydrateIcons(root = document) { $$('[data-icon]', root).forEach((node) => { node.innerHTML = icon(node.dataset.icon); }); }
  function esc(value) { return String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function money(value) { const number = Number(value); return Number.isFinite(number) ? new Intl.NumberFormat('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(number) : '—'; }
  function int(value) { return Number.isFinite(Number(value)) ? new Intl.NumberFormat('zh-CN').format(Number(value)) : '—'; }
  function timeNow() { return new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date()); }
  function uid(prefix) { return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`; }
  function toast(message, type = 'info') { const stack = $('#toast-stack'); const node = document.createElement('div'); node.className = `toast ${type}`; node.innerHTML = `${icon(type === 'success' ? 'check-circle' : type === 'error' ? 'alert' : 'info')}<span>${esc(message)}</span>`; stack.appendChild(node); setTimeout(() => node.remove(), 3200); }
  function normalize(value) { return String(value ?? '').toLowerCase().replace(/[\s_\-./（）()：:]/g, ''); }
  function findHeader(headers, patterns) { return headers.find((header) => { const n = normalize(header); return patterns.some((pattern) => n.includes(normalize(pattern))); }) || ''; }
  function numberValue(value) { if (value === null || value === undefined || String(value).trim() === '') return 0; const n = Number(String(value).replace(/[^\d.-]/g, '')); return Number.isFinite(n) ? n : 0; }
  function dateValue(value) { if (!value) return null; const text = String(value).trim().replace(/[./年]/g, '-').replace(/月/g, '-').replace(/日/g, ''); const date = new Date(text); return Number.isNaN(date.getTime()) ? null : date; }
  function rowText(row, header) { return header ? String(row[header] ?? '').trim() : ''; }
  function firstExisting(headers, patterns) { return findHeader(headers, patterns); }
  function addFinding(findings, tool, severity, type, record, detail, source, suggestion) { findings.push({ id: `${tool.toUpperCase()}-${String(findings.length + 1).padStart(3, '0')}`, severity, type, record, detail, source, suggestion }); }

  const toolCatalog = [
    { id: 'cash', code: 'A01', name: '现金与银行', short: '银行存款调节与未达账项', icon: 'bank', color: 'blue', category: '货币资金', description: '核对银行流水、账面余额、重复流水和期末调节项目。', required: [['date', '日期'], ['amount', '金额 / 借方 / 贷方']], rules: ['账户、日期、金额、流水号组合匹配', '期初 + 收 − 付 = 期末', '重复银行流水号和交易指纹'], outputs: ['账户级调节表', '未匹配项目清单', '重复流水清单'] },
    { id: 'revenue', code: 'A02', name: '收入与截止', short: '发票、发货与收入期间', icon: 'revenue', color: 'teal', category: '收入循环', description: '识别期末前后发票、发货、入账日期差异及重复收入。', required: [['invoiceDate', '发票日期'], ['amount', '金额 / 收入']], rules: ['期末前后 ±5 天截止窗口', '发票、发货、入账日期交叉比较', '发票号和客户金额重复检测'], outputs: ['截止性样本清单', '日期差异表', '重复发票清单'] },
    { id: 'procurement', code: 'A03', name: '采购与付款', short: 'PO、验收、发票和付款', icon: 'purchase', color: 'amber', category: '采购循环', description: '执行三单匹配，筛查重复发票、拆单和缺少验收的交易。', required: [['po', '订单金额 / PO'], ['invoice', '发票金额 / Invoice']], rules: ['订单—验收—发票金额差异', '供应商 + 发票号重复', '缺少订单、验收或发票'], outputs: ['三单匹配表', '重复付款登记', '待补资料清单'] },
    { id: 'inventory', code: 'A04', name: '存货与盘点', short: '数量滚动与估值差异', icon: 'inventory', color: 'purple', category: '存货', description: '重算数量滚动、延伸金额和负数 / 零成本异常。', required: [['opening', '期初数量'], ['closing', '期末数量']], rules: ['期初 + 入库 − 出库 ± 调整 = 期末', '数量 × 单位成本 = 账面金额', '负数、零成本、负成本项目'], outputs: ['数量滚动表', '估值差异表', '盘点差异清单'] },
    { id: 'expense', code: 'A05', name: '费用与报销', short: '真实性、授权与重复', icon: 'expense', color: 'coral', category: '费用循环', description: '从发票、摘要、日期和收款账户识别报销异常。', required: [['date', '日期'], ['amount', '金额']], rules: ['发票号 / 日期 / 金额重复', '缺少发票或业务摘要', '整数金额和关键词筛查'], outputs: ['报销异常表', '重复费用清单', '资料补充清单'] },
    { id: 'payroll', code: 'A06', name: '薪酬与工资', short: '工资表勾稽与人员主数据', icon: 'payroll', color: 'blue', category: '薪酬', description: '复核应发、扣款、实发、账户和员工主数据的一致性。', required: [['employee', '员工编号 / 姓名'], ['gross', '应发 / 实发']], rules: ['工时 × 费率与应发比较', '员工编号、账户重复', '负实发和离职后付款'], outputs: ['工资表复核表', '人员主数据差异', '付款异常清单'] },
    { id: 'journal', code: 'A07', name: '凭证与异常', short: '借贷平衡、重复和手工分录', icon: 'journal', color: 'violet', category: '账簿完整性', description: '检查凭证借贷平衡、重复来源、金额和异常摘要。', required: [['voucher', '凭证号'], ['debit', '借方 / 贷方']], rules: ['凭证借贷平衡', '来源、摘要、金额指纹重复', '大额、关键词和手工分录'], outputs: ['凭证平衡表', '异常分录清单', '调整建议记录'] }
  ];

  const sampleData = {
    cash: { name: '示例_银行流水.csv', headers: ['账户', '日期', '银行流水号', '摘要', '借方', '贷方', '账面余额', '银行余额'], rows: [
      { 账户: '基本户', 日期: '2025-12-29', 银行流水号: 'B-1001', 摘要: '销售回款', 借方: '180000', 贷方: '', 账面余额: '1180000', 银行余额: '1180000' },
      { 账户: '基本户', 日期: '2025-12-30', 银行流水号: 'B-1002', 摘要: '供应商付款', 借方: '', 贷方: '260000', 账面余额: '920000', 银行余额: '920000' },
      { 账户: '基本户', 日期: '2025-12-31', 银行流水号: 'B-1001', 摘要: '销售回款', 借方: '180000', 贷方: '', 账面余额: '1100000', 银行余额: '920000' },
      { 账户: '基本户', 日期: '2026-01-02', 银行流水号: 'B-1003', 摘要: '手续费', 借方: '', 贷方: '1200', 账面余额: '1098800', 银行余额: '918800' }
    ] },
    revenue: { name: '示例_收入截止.csv', headers: ['发票号', '客户', '发票日期', '发货日期', '入账日期', '金额', '收入科目'], rows: [
      { 发票号: 'INV-25001', 客户: '华东客户', 发票日期: '2025-12-28', 发货日期: '2025-12-30', 入账日期: '2025-12-31', 金额: '128000', 收入科目: '6001' },
      { 发票号: 'INV-25002', 客户: '华南客户', 发票日期: '2025-12-31', 发货日期: '2026-01-03', 入账日期: '2025-12-31', 金额: '86000', 收入科目: '6001' },
      { 发票号: 'INV-25001', 客户: '华东客户', 发票日期: '2025-12-28', 发货日期: '2025-12-30', 入账日期: '2025-12-31', 金额: '128000', 收入科目: '6001' },
      { 发票号: 'INV-25003', 客户: '北方客户', 发票日期: '2026-01-02', 发货日期: '2026-01-02', 入账日期: '2026-01-02', 金额: '42000', 收入科目: '6001' }
    ] },
    procurement: { name: '示例_采购三单.csv', headers: ['供应商', '采购订单号', '验收单号', '发票号', '订单金额', '验收金额', '发票金额', '付款日期', '收款账户'], rows: [
      { 供应商: '星河科技', 采购订单号: 'PO-001', 验收单号: 'GR-001', 发票号: 'AP-001', 订单金额: '100000', 验收金额: '100000', 发票金额: '100000', 付款日期: '2025-12-20', 收款账户: '6222-001' },
      { 供应商: '北辰咨询', 采购订单号: 'PO-002', 验收单号: 'GR-002', 发票号: 'AP-002', 订单金额: '80000', 验收金额: '80000', 发票金额: '76000', 付款日期: '2025-12-28', 收款账户: '6222-002' },
      { 供应商: '星河科技', 采购订单号: 'PO-003', 验收单号: 'GR-003', 发票号: 'AP-001', 订单金额: '100000', 验收金额: '100000', 发票金额: '100000', 付款日期: '2025-12-20', 收款账户: '6222-001' }
    ] },
    inventory: { name: '示例_存货滚动.csv', headers: ['物料', '仓库', '期初数量', '入库', '出库', '调整', '期末数量', '单位成本', '金额'], rows: [
      { 物料: 'A-001 电机', 仓库: '华东仓', 期初数量: '1000', 入库: '300', 出库: '240', 调整: '-2', 期末数量: '1058', 单位成本: '120', 金额: '126960' },
      { 物料: 'A-002 控制器', 仓库: '华南仓', 期初数量: '500', 入库: '100', 出库: '480', 调整: '', 期末数量: '120', 单位成本: '260', 金额: '31200' },
      { 物料: 'A-003 传感器', 仓库: '北方仓', 期初数量: '200', 入库: '0', 出库: '0', 调整: '0', 期末数量: '0', 单位成本: '0', 金额: '0' }
    ] },
    expense: { name: '示例_费用报销.csv', headers: ['员工', '日期', '类别', '供应商', '发票号', '金额', '摘要', '收款账户'], rows: [
      { 员工: '张敏', 日期: '2025-12-06', 类别: '交通', 供应商: '滴滴出行', 发票号: 'D-1001', 金额: '368.00', 摘要: '客户拜访', 收款账户: '个人账户' },
      { 员工: '张敏', 日期: '2025-12-06', 类别: '交通', 供应商: '滴滴出行', 发票号: 'D-1001', 金额: '368.00', 摘要: '客户拜访', 收款账户: '个人账户' },
      { 员工: '李强', 日期: '2025-12-28', 类别: '咨询', 供应商: '北辰咨询', 发票号: 'C-2001', 金额: '50000.00', 摘要: '', 收款账户: '个人账户' }
    ] },
    payroll: { name: '示例_工资表.csv', headers: ['员工编号', '姓名', '部门', '期间', '工时', '费率', '应发', '扣款', '实发', '账户'], rows: [
      { 员工编号: 'E-001', 姓名: '王芳', 部门: '财务', 期间: '2025-12', 工时: '160', 费率: '120', 应发: '19200', 扣款: '1800', 实发: '17400', 账户: 'A-001' },
      { 员工编号: 'E-002', 姓名: '陈磊', 部门: '销售', 期间: '2025-12', 工时: '160', 费率: '100', 应发: '15000', 扣款: '1200', 实发: '13800', 账户: 'A-002' },
      { 员工编号: 'E-001', 姓名: '王芳', 部门: '财务', 期间: '2025-12', 工时: '160', 费率: '120', 应发: '19200', 扣款: '1800', 实发: '17400', 账户: 'A-001' }
    ] },
    journal: { name: '示例_凭证明细.csv', headers: ['凭证号', '日期', '科目', '借方', '贷方', '摘要', '来源', '制单人'], rows: [
      { 凭证号: '记-001', 日期: '2025-12-31', 科目: '管理费用', 借方: '50000', 贷方: '', 摘要: '咨询费', 来源: '手工', 制单人: 'admin' },
      { 凭证号: '记-001', 日期: '2025-12-31', 科目: '银行存款', 借方: '', 贷方: '45000', 摘要: '咨询费', 来源: '手工', 制单人: 'admin' },
      { 凭证号: '记-002', 日期: '2025-12-31', 科目: '管理费用', 借方: '50000', 贷方: '', 摘要: '咨询费', 来源: '手工', 制单人: 'admin' },
      { 凭证号: '记-003', 日期: '2026-01-01', 科目: '管理费用', 借方: '80000', 贷方: '', 摘要: '预付咨询费', 来源: '手工', 制单人: 'admin' }
    ] }
  };

  const fallbackWorkspace = {
    version: 1, projects: [{ id: 'p-demo', name: '年度财务报表审计', client: '示例客户', period: '2025 年度', status: '进行中', progress: 62, updatedAt: '今天', areas: ['货币资金', '收入', '采购', '存货'] }], activeProjectId: 'p-demo',
    tasks: [{ id: 't-1', title: '完成银行存款函证及受限资金核对', area: '货币资金', priority: '高', due: '今天', done: false }, { id: 't-2', title: '复核收入截止性测试样本', area: '收入循环', priority: '高', due: '明天', done: false }, { id: 't-3', title: '抽查 30 笔费用报销单据', area: '费用报销', priority: '中', due: '周五', done: false }, { id: 't-4', title: '整理抽样底稿与证据索引', area: '底稿管理', priority: '低', due: '下周', done: true }], evidence: [], notes: []
  };
  let workspace = clone(fallbackWorkspace);
  let settings = { endpoint: '', model: 'gpt-4o-mini', temperature: 0.2, systemPrompt: '你是审计工作助手。区分事实、假设和建议，不把异常线索直接表述为审计结论。', hasApiKey: false };
  let currentView = 'overview';
  let activeToolId = null;
  let importedData = null;
  let toolResult = null;
  let knowledgeFiles = [];
  let activeKnowledge = null;
  let knowledgeSearch = '';
  let settingsTab = 'api';
  let assistantHistory = [];
  let assistantBusy = false;
  let appInfo = null;
  let vendorCache = null;
  async function paintVendors() { const box = $('#vendor-box'); if (!box || !bridge) return; if (!vendorCache) { try { vendorCache = await bridge.listVendors(); } catch { vendorCache = []; } } box.innerHTML = vendorCache.length ? vendorCache.map((item) => `<div class="readiness-row"><span>${esc(item.name)}</span><strong class="${item.available ? 'ok' : 'bad'}">${item.available ? '已内置' : '缺失'}</strong></div>`).join('') : '<div class="readiness-row"><span>内置组件</span><strong>未检测到</strong></div>'; }

  async function init() {
    if (bridge) {
      try { workspace = await bridge.readWorkspace(); settings = await bridge.readSettings(); appInfo = await bridge.appInfo(); } catch (error) { console.warn(error); }
    }
    hydrateIcons();
    bindShell();
    render();
    if (bridge) {
      try { knowledgeFiles = await bridge.listKnowledge(); } catch (error) { knowledgeFiles = []; }
      render();
    }
  }

  function activeProject() { return workspace.projects?.find((project) => project.id === workspace.activeProjectId) || workspace.projects?.[0] || {}; }
  function currentTool() { return toolCatalog.find((tool) => tool.id === activeToolId); }
  function saveWorkspace() { if (bridge) bridge.writeWorkspace(workspace).catch((error) => toast(`保存失败：${error.message}`, 'error')); }
  async function saveNow() { if (!bridge) { toast('桌面应用中才可保存。', 'info'); return; } try { await bridge.writeWorkspace(workspace); toast('项目已保存到本地。', 'success'); } catch (error) { toast(`保存失败：${error.message}`, 'error'); } }
  function projectProgress() { const tasks = workspace.tasks || []; const evidence = workspace.evidence || []; const taskScore = tasks.length ? tasks.filter((task) => task.done).length / tasks.length : 0; const evScore = evidence.length ? evidence.filter((item) => item.status === '已完成').length / evidence.length : 0; return Math.round(taskScore * 60 + evScore * 40); }
  function bindDropZone() { const drop = $('#drop-zone'); if (!drop || drop.dataset.bound) return; drop.dataset.bound = '1'; ['dragenter', 'dragover'].forEach((name) => drop.addEventListener(name, (event) => { event.preventDefault(); drop.classList.add('dragover'); })); ['dragleave', 'drop'].forEach((name) => drop.addEventListener(name, (event) => { event.preventDefault(); drop.classList.remove('dragover'); })); drop.addEventListener('drop', async (event) => { const file = event.dataTransfer.files?.[0]; if (!file || !bridge) return; try { const buffer = await file.arrayBuffer(); const text = new TextDecoder('utf-8').decode(buffer); const parsed = parseCsvText(text); importedData = { ...parsed, name: file.name, size: file.size, format: 'CSV' }; toolResult = null; render(); toast(`已载入 ${file.name}`, 'success'); } catch (error) { toast(`读取失败：${error.message}`, 'error'); } }); }
  function paintNotes() { const input = $('#evidence-note'); if (!input) return; let list = $('#notes-list'); if (!list) { list = document.createElement('div'); list.id = 'notes-list'; list.className = 'note-list'; input.after(list); } const notes = workspace.notes || []; list.innerHTML = notes.length ? notes.slice(0, 8).map((note) => `<div class="note-item"><p>${esc(note.text)}</p><time>${esc(note.time)}</time></div>`).join('') : ''; }
  function updateChrome() { const project = activeProject(); $('#sidebar-project').textContent = project.name || '未选择项目'; $('#context-period').textContent = project.period || '未设置期间'; const dataBadge = $('#data-badge'); if (dataBadge) dataBadge.textContent = importedData ? '1' : '0'; const evidenceBadge = $('#evidence-badge'); if (evidenceBadge) evidenceBadge.textContent = workspace.evidence?.filter((item) => item.status !== '已完成').length || 0; $$('.nav-item[data-view]').forEach((item) => item.classList.toggle('active', item.dataset.view === currentView)); const crumb = $('#crumb'); if (crumb) crumb.textContent = ({ overview: '项目总览', data: '数据与导入', procedures: '审计程序', knowledge: '学习资料', evidence: '底稿与证据', settings: '项目设置' })[currentView] || '项目总览'; }

  function render() { const root = $('#content'); if (!root) return; root.innerHTML = currentView === 'overview' ? renderOverview() : currentView === 'data' ? renderData() : currentView === 'procedures' ? renderProcedures() : currentView === 'knowledge' ? renderKnowledge() : currentView === 'evidence' ? renderEvidence() : renderSettings(); hydrateIcons(root); updateChrome(); bindDropZone(); paintNotes(); paintVendors(); }

  function renderOverview() {
    const project = activeProject(); const openTasks = (workspace.tasks || []).filter((task) => !task.done); const projectEvidence = workspace.evidence || [];
    return `<div class="page-head"><div><p class="page-kicker">审计项目 / ${esc(project.period || '未设置期间')}</p><h1>项目总览</h1><p>以确定性检查为主线，把数据、程序、底稿和证据放在同一个工作区。</p></div><div class="head-actions"><button class="btn primary" data-action="open-procedures">进入审计程序 ${icon('chevron-right')}</button></div></div>
      <div class="overview-grid"><div class="overview-main"><div class="project-banner"><div class="project-banner-copy"><p class="page-kicker">当前项目</p><h2>${esc(project.name || '未命名项目')}</h2><p>${esc(project.client || '未设置客户')} · ${esc(project.status || '进行中')} · 最近更新 ${esc(project.updatedAt || '—')}</p></div><div class="project-meta"><div><span>总体进度</span><strong>${projectProgress()}%</strong><small>待办与证据完成度</small></div><div><span>待办事项</span><strong>${int(openTasks.length)}</strong><small>${int(openTasks.filter((task) => task.priority === '高').length)} 项高优先级</small></div><div><span>证据缺口</span><strong>${int(projectEvidence.filter((item) => item.status !== '已完成').length)}</strong><small>待复核或待补充</small></div><div><span>当前工作区</span><strong>本地</strong><small>无云端上传</small></div></div></div>
        <div class="section-title"><h2>重点审计模块</h2><span>选择模块开始程序</span></div><div class="module-strip">${toolCatalog.map((tool) => moduleCard(tool)).join('')}</div>
        <div class="overview-columns"><div class="card"><div class="card-head"><div><h2>待办事项</h2><p>只显示当前项目的执行清单</p></div><button class="btn small ghost" data-action="new-task">${icon('plus')}新增待办</button></div><div class="card-body"><table class="task-table"><thead><tr><th></th><th>事项</th><th>优先级</th><th>截止</th></tr></thead><tbody>${(workspace.tasks || []).slice(0, 6).map((task) => taskRow(task)).join('')}</tbody></table></div></div>${renderProgressCard(project)}</div></div><aside class="overview-side"><div class="card"><div class="card-head"><div><h2>数据准备</h2><p>最近一次导入与检查状态</p></div><button class="btn small ghost" data-view="data">管理数据</button></div><div class="card-body">${renderDataSummary()}</div></div><div class="card"><div class="card-head"><div><h2>最近证据</h2><p>底稿和资料索引</p></div><button class="btn small ghost" data-view="evidence">全部 ${icon('chevron-right')}</button></div><div class="card-body">${renderSourceList(projectEvidence.slice(0, 4))}</div></div></aside></div>`;
  }
  function moduleCard(tool) { const status = importedData ? 'ready' : 'missing'; const state = importedData ? '已导入' : '待导入'; return `<button class="module-card" data-tool="${tool.id}"><div class="module-top"><span class="module-icon">${icon(tool.icon)}</span><span class="status-pill ${status}">${state}</span></div><h3>${tool.name}</h3><p>${tool.short}</p></button>`; }
  function taskRow(task) { return `<tr class="${task.done ? 'done' : ''}"><td><button class="task-check" data-action="toggle-task" data-task="${task.id}">${task.done ? '✓' : ''}</button></td><td><span class="task-title">${esc(task.title)}</span><span class="task-area">${esc(task.area)}</span></td><td><span class="priority ${task.priority === '高' ? 'high' : task.priority === '中' ? 'medium' : 'low'}">${esc(task.priority)}</span></td><td>${esc(task.due)}</td></tr>`; }
  function renderProgressCard(project) { const progress = projectProgress(); return `<div class="card progress-card"><div class="card-head"><div><h2>项目进度</h2><p>按底稿完成度记录，不自动推断结论</p></div></div><div class="progress-body"><div class="progress-top"><strong>${progress}%</strong><span>${progress >= 100 ? '已完成' : '进行中'}</span></div><div class="progress-track"><span style="width:${progress}%"></span></div><div class="progress-stages"><div class="progress-stage done">准备</div><div class="progress-stage ${progress >= 35 ? 'done' : 'current'}">风险</div><div class="progress-stage ${progress >= 65 ? 'done' : progress >= 35 ? 'current' : ''}">程序</div><div class="progress-stage ${progress >= 90 ? 'done' : progress >= 65 ? 'current' : ''}">复核</div></div><div class="notice">${icon('info')}每一项异常都需要回到源数据和证据，不自动生成审计结论。</div></div></div>`; }
  function renderDataSummary() { if (!importedData) return `<div class="empty-state" style="min-height:170px;border:0;padding:12px">${icon('database')}<h3>尚未导入数据</h3><p>导入 CSV、XLSX 或 JSON 后，模块会显示字段就绪状态。</p><button class="btn small primary" data-action="open-file">选择数据文件</button></div>`; const info = inspectTable(importedData); return `<div class="data-summary"><div class="summary-number"><span>当前文件</span><strong>${int(info.rowsCount)}</strong></div><div class="summary-number"><span>字段数</span><strong>${int(info.columns)}</strong></div><div class="summary-number"><span>可运行程序</span><strong>${int(info.readyTools)}</strong></div></div><div class="source-list"><div class="source-row"><span class="source-icon">${icon('file')}</span><div class="source-copy"><strong>${esc(importedData.name)}</strong><span>${esc(importedData.format || importedData.delimiter || 'TABLE')} · ${esc(formatSize(importedData.size))}</span></div><span class="source-time">已载入</span></div><div class="source-row"><span class="source-icon">${icon('shield')}</span><div class="source-copy"><strong>${info.readyTools ? '字段基本可用' : '需要确认字段'}</strong><span>${info.readyTools ? '可以进入确定性检查' : '请在程序页确认字段映射'}</span></div><span class="source-time">就绪</span></div></div>`; }
  function renderSourceList(items) { if (!items?.length) return '<div class="empty-state" style="min-height:145px;border:0;padding:8px"><h3>暂无证据</h3><p>在底稿与证据中登记第一条记录。</p></div>'; return `<div class="source-list">${items.map((item) => `<div class="source-row"><span class="source-icon">${icon('file')}</span><div class="source-copy"><strong>${esc(item.title)}</strong><span>${esc(item.code)} · ${esc(item.status)}</span></div><span class="source-time">${esc(item.updatedAt || '')}</span></div>`).join('')}</div>`; }

  function renderTable(headers = [], rows = [], limit = 100) { if (!headers.length || !rows.length) return '<div class="empty-result"><div><h3>暂无可预览数据</h3></div></div>'; return `<table class="data-table"><thead><tr>${headers.map((header) => `<th>${esc(header)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0, limit).map((row) => `<tr>${headers.map((header) => `<td title="${esc(row[header])}">${esc(row[header] || '—')}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }

  function renderData() {
    return `<div class="page-head"><div><p class="page-kicker">数据与导入</p><h1>数据准备</h1><p>保留源文件、确认字段和总体完整性，再运行审计程序。文件只在本地读取。</p></div><div class="head-actions"><button class="btn" data-action="load-sample-menu">${icon('file')}载入示例</button>${importedData ? '<button class="btn" data-action="open-sql">SQL 工作台</button>' : ''}<button class="btn primary" data-action="open-file">${icon('upload')}导入 CSV / XLSX</button></div></div><div class="data-layout"><div class="card"><div class="card-head"><div><h2>当前数据源</h2><p>支持 CSV、TSV、XLSX 和 JSON；PDF 作为待处理文档登记</p></div>${importedData ? '<span class="status-pill ready">已载入</span>' : '<span class="status-pill missing">未载入</span>'}</div>${importedData ? renderDataFileCard() : `<div class="card-body"><div class="drop-zone" id="drop-zone"><span class="drop-icon">${icon('upload')}</span><strong>拖拽文件到这里，或点击选择</strong><p>不会上传到云端 · 单次最多读取 200,000 行</p><button class="btn small primary" data-action="open-file">选择文件</button></div></div>`}</div><aside class="card"><div class="card-head"><div><h2>字段就绪检查</h2><p>按程序推断可用字段</p></div></div><div class="card-body">${renderReadiness()}</div></aside></div>${importedData ? `<div class="section-title"><h2>源数据预览</h2><span>${int(importedData.rows?.length || 0)} 行 · ${int(importedData.headers?.length || 0)} 列</span></div><div class="card"><div class="table-wrap">${renderTable(importedData.headers, importedData.rows, 8)}</div></div>` : ''}`;
  }
  function renderDataFileCard() { const info = inspectTable(importedData); return `<div class="card-body"><div class="file-card"><span class="file-icon">${icon('file')}</span><div class="file-copy"><strong>${esc(importedData.name)}</strong><span>${esc(formatSize(importedData.size))} · ${esc(importedData.format || importedData.delimiter || 'TABLE')}</span></div><button class="icon-button" data-action="remove-data">${icon('x')}</button></div><div class="data-summary"><div class="summary-number"><span>记录数</span><strong>${int(info.rowsCount)}</strong></div><div class="summary-number"><span>字段数</span><strong>${int(info.columns)}</strong></div><div class="summary-number"><span>缺失单元格</span><strong>${int(info.missing)}</strong></div></div><div class="head-actions" style="margin-top:14px"><button class="btn small" data-action="open-procedures">选择审计程序 ${icon('chevron-right')}</button><button class="btn small ghost" data-action="export-source">导出字段摘要</button></div></div>`; }
  function renderReadiness() { if (!importedData) return `<div class="data-readiness"><div class="readiness-row"><span>文件完整性</span><strong>待导入</strong></div><div class="readiness-row"><span>字段识别</span><strong>待导入</strong></div><div class="readiness-row"><span>总体确认</span><strong>待确认</strong></div><div class="notice">${icon('info')}不完整总体只能生成“待补充”状态，不能直接得出通过结论。</div></div>`; const info = inspectTable(importedData); return `<div class="data-readiness"><div class="readiness-row"><span>文件完整性</span><strong class="ok">已读取</strong></div><div class="readiness-row"><span>字段识别</span><strong class="${info.columns ? 'ok' : 'warn'}">${info.columns} 个字段</strong></div><div class="readiness-row"><span>缺失单元格</span><strong class="${info.missing > 0 ? 'warn' : 'ok'}">${int(info.missing)} 个</strong></div><div class="readiness-row"><span>可运行程序</span><strong class="${info.readyTools ? 'ok' : 'warn'}">${int(info.readyTools)} / ${toolCatalog.length}</strong></div><table class="mapping-table"><thead><tr><th>程序</th><th>识别字段</th><th>状态</th></tr></thead><tbody>${toolCatalog.map((tool) => `<tr><td>${tool.name}</td><td>${esc(toolReady(tool).found.join('、') || '未识别')}</td><td class="${toolReady(tool).ready ? '' : 'muted'}">${toolReady(tool).ready ? '可运行' : '需映射'}</td></tr>`).join('')}</tbody></table></div>`; }
  function inspectTable(data) { const headers = data?.headers || []; const rows = data?.rows || []; const missing = rows.reduce((sum, row) => sum + headers.filter((header) => String(row[header] ?? '').trim() === '').length, 0); const readyTools = toolCatalog.filter((tool) => toolReady(tool, data).ready).length; return { headers, rows, columns: headers.length, rowsCount: rows.length, missing, readyTools }; }
  function toolReady(tool, data = importedData) { const headers = data?.headers || []; const found = tool.required.map(([key, patterns]) => [key, findHeader(headers, patterns.split(' / '))]).filter(([, header]) => header).map(([key, header]) => `${key}:${header}`); return { ready: found.length >= Math.max(1, Math.ceil(tool.required.length * .6)), found, headers }; }

  function renderProcedures() { if (activeToolId) return renderToolWorkbench(); const recent = toolResult ? `<div class="section-title"><h2>最近一次运行</h2><span>${esc(toolResult.toolName)} · ${esc(toolResult.createdAt)}</span></div><div class="card"><div class="card-body"><div class="data-summary"><div class="summary-number"><span>总体记录</span><strong>${int(toolResult.population)}</strong></div><div class="summary-number"><span>异常项目</span><strong>${int(toolResult.findings.length)}</strong></div><div class="summary-number"><span>最高等级</span><strong>${toolResult.findings.some((item) => item.severity === '高') ? '高' : toolResult.findings.length ? '中' : '—'}</strong></div></div><div class="head-actions" style="margin-top:13px"><button class="btn small" data-action="view-last-result">查看结果</button></div></div></div>` : ''; return `<div class="page-head"><div><p class="page-kicker">审计程序 / 七个高频模块</p><h1>审计程序</h1><p>每个程序都遵循同一套流程：确认输入、运行规则、复核异常、沉淀底稿。</p></div><div class="head-actions"><button class="btn" data-action="open-guide">查看工作标准</button><button class="btn primary" data-action="open-file">${icon('upload')}导入数据</button></div></div><div class="tool-grid">${toolCatalog.map((tool) => toolCard(tool)).join('')}</div>${recent}`; }
  function toolCard(tool) { const state = importedData ? toolReady(tool).ready ? '字段可运行' : '需确认字段' : '等待数据'; return `<button class="tool-card" data-tool="${tool.id}"><div class="tool-card-head"><span class="tool-card-icon">${icon(tool.icon)}</span><span class="status-pill ${importedData && toolReady(tool).ready ? 'ready' : 'missing'}">${state}</span></div><h3>${tool.name}</h3><p>${tool.description}</p><div class="tool-card-foot"><span>${tool.code}</span><span>${tool.category}</span><span class="tool-state">${icon('chevron-right')}</span></div></button>`; }
  function renderToolWorkbench() { const tool = currentTool(); if (!tool) return ''; const result = toolResult?.toolId === tool.id ? toolResult : null; const readiness = result?.readiness || toolReady(tool); const findings = result?.findings || []; return `<div class="workbench-head"><div class="workbench-title"><button class="back-link" data-action="back-procedures">${icon('arrow-left')}审计程序</button><div><h1>${tool.name}</h1><p>${tool.code} · ${tool.short}</p></div></div><div class="workbench-actions"><button class="btn" data-action="load-tool-sample">${icon('file')}载入样例</button><button class="btn" data-action="open-file">${icon('upload')}导入数据</button><button class="btn primary" data-action="run-tool" ${importedData ? '' : 'disabled'}>${icon('play')}运行检查</button></div></div><div class="workbench-layout"><aside class="work-pane"><div class="pane-head"><h2>程序说明</h2><p>目标、输入与就绪条件</p></div><div class="pane-body"><p class="objective">对${tool.name}相关总体执行透明、可复现的确定性检查，输出需要人工复核的异常线索。</p><div class="check-list">${tool.required.map(([key, label]) => { const found = readiness.headers?.length ? findHeader(readiness.headers, label.split(' / ')) : ''; return `<div class="check-item ${found ? 'ready' : 'missing'}"><i>${found ? '✓' : ''}</i><div><strong>${label}</strong><span>${found ? `已识别：${found}` : '需要确认字段'}</span></div></div>`; }).join('')}</div></div></aside><section class="work-pane"><div class="result-head"><h2>${result ? '测试结果' : '数据结果'}</h2><span>${result ? `${int(result.population)} 条总体 · ${int(findings.length)} 条异常` : '导入或载入样例后开始'}</span></div>${result ? `<div class="result-metrics">${result.metrics.map((metric) => `<div class="result-metric ${metric.level || ''}"><span>${metric.label}</span><strong>${metric.value}</strong></div>`).join('')}</div><div class="table-wrap">${findings.length ? renderFindingsTable(findings) : `<div class="empty-result"><div>${icon('check-circle')}<h3>本次未命中预设规则</h3><p>这不等于没有风险；请确认总体完整、字段口径和人工复核范围。</p></div></div>`}</div>` : `<div class="empty-result"><div>${icon('database')}<h3>尚未运行检查</h3><p>导入数据后点击“运行检查”。你也可以先载入本模块的示例数据。</p><button class="btn small primary" data-action="load-tool-sample">载入样例</button></div></div>`}</section><aside class="work-pane side"><div class="pane-head"><h2>规则与输出</h2><p>规则会写入结果摘要</p></div><div class="pane-body"><div class="rule-list">${tool.rules.map((rule, index) => `<div class="rule-item"><strong>R-${String(index + 1).padStart(2, '0')} · ${rule}</strong><p>计算透明；异常只进入待复核清单，不自动定性。</p></div>`).join('')}</div><div class="section-title" style="margin-top:19px"><h2>预期输出</h2></div><div class="rule-list">${tool.outputs.map((output) => `<div class="rule-item"><strong>${output}</strong><p>可导出为 CSV / JSON，并登记到底稿索引。</p></div>`).join('')}</div><div class="notice">${icon('info')}请记录总体范围、运行时间、规则参数和复核人。</div></div></aside></div>`; }
  function renderFindingsTable(findings) { return `<table class="data-table"><thead><tr><th>编号</th><th>等级</th><th>类型</th><th>记录</th><th>发现线索</th><th>建议动作</th></tr></thead><tbody>${findings.map((finding) => `<tr><td class="finding-id">${esc(finding.id)}</td><td><span class="severity ${finding.severity === '高' ? 'high' : finding.severity === '中' ? 'medium' : 'low'}">${esc(finding.severity)}</span></td><td>${esc(finding.type)}</td><td>${esc(finding.record)}</td><td title="${esc(finding.detail)}">${esc(finding.detail)}</td><td title="${esc(finding.suggestion)}">${esc(finding.suggestion)}</td></tr>`).join('')}</tbody></table>`; }

  function renderKnowledge() { const files = knowledgeFiles.filter((file) => !knowledgeSearch || file.name.toLowerCase().includes(knowledgeSearch.toLowerCase())); const selected = activeKnowledge || files[0]; return `<div class="page-head"><div><p class="page-kicker">学习资料 / 本地资料库</p><h1>学习资料</h1><p>把审计方法、程序模板、字段字典和项目记录放在本地，不依赖外部知识库。</p></div><div class="head-actions"><button class="btn" data-action="open-external" data-url="https://www.cicpa.org.cn/">打开官方资料</button></div></div><div class="knowledge-layout"><aside class="card knowledge-list"><div class="knowledge-filter"><input id="knowledge-search" value="${esc(knowledgeSearch)}" placeholder="搜索资料名称…" /></div>${files.length ? files.map((file) => `<button class="knowledge-link ${selected?.relative === file.relative ? 'active' : ''}" data-knowledge="${esc(file.relative)}"><strong>${esc(file.name.replace(/\.(md|html|txt)$/i, ''))}</strong><span>${formatSize(file.size)} · 本地资料</span></button>`).join('') : '<div class="empty-state" style="min-height:170px;border:0;padding:14px"><h3>资料库为空</h3><p>将 Markdown 文档放入 resources/knowledge。</p></div>'}</aside><article class="card knowledge-doc" id="knowledge-content">${selected ? '<div class="doc-loading">正在读取…</div>' : '<div class="empty-state"><h3>选择一份资料</h3></div>'}</article></div>`; }

  function renderEvidence() { const evidence = workspace.evidence || []; const issues = toolResult?.findings || []; return `<div class="page-head"><div><p class="page-kicker">底稿与证据</p><h1>底稿与证据</h1><p>登记程序结果、证据来源、复核状态和未解决事项。</p></div><div class="head-actions"><button class="btn" data-action="add-evidence">${icon('plus')}新增证据</button><button class="btn primary" data-action="export-workspace">${icon('download')}导出工作区</button></div></div><div class="evidence-layout"><div class="card"><div class="card-head"><div><h2>证据索引</h2><p>原始文件、程序结果和复核状态</p></div><span class="status-pill ready">${int(evidence.length)} 条</span></div><div class="card-body">${evidence.length ? `<table class="evidence-table"><thead><tr><th>编号 / 标题</th><th>类型</th><th>状态</th><th>来源</th><th>更新</th></tr></thead><tbody>${evidence.map((item) => `<tr><td><strong>${esc(item.code)}</strong> ${esc(item.title)}<small>${esc(item.source || '')}</small></td><td>${esc(item.type)}</td><td><span class="status-pill ${item.status === '已完成' ? 'ready' : item.status === '待复核' ? 'review' : 'missing'}">${esc(item.status)}</span></td><td>${esc(item.source || '—')}</td><td>${esc(item.updatedAt || '—')}</td></tr>`).join('')}</tbody></table>` : '<div class="empty-state" style="min-height:220px;border:0"><h3>暂无证据记录</h3><p>先新增一条底稿索引，再把程序结果关联进来。</p></div>'}</div></div><aside><div class="card"><div class="card-head"><div><h2>最近程序异常</h2><p>来自最近一次工具运行</p></div></div><div class="card-body">${issues.length ? `<div class="issue-list">${issues.slice(0, 6).map((issue) => `<div class="issue-row"><strong>${esc(issue.id)} · ${esc(issue.type)}</strong><p>${esc(issue.detail)}</p><div class="issue-footer"><span>${esc(issue.severity)}级</span><button data-action="save-issue" data-finding="${esc(issue.id)}">登记为问题</button></div></div>`).join('')}</div>` : '<div class="empty-state" style="min-height:180px;border:0"><h3>暂无异常</h3><p>运行一个审计程序后，异常会显示在这里。</p></div>'}</div></div><div class="card" style="margin-top:15px"><div class="card-head"><div><h2>快速笔记</h2><p>记录需要补充的资料</p></div></div><div class="card-body"><textarea id="evidence-note" rows="4" placeholder="例如：补充 12 月 31 日前后发货签收记录…" style="width:100%;padding:9px;border:1px solid var(--line);border-radius:5px;resize:vertical;font-size:9px"></textarea><button class="btn small primary" style="margin-top:8px" data-action="add-note">保存笔记</button></div></div></aside></div>`; }

  function renderSettings() { return `<div class="page-head"><div><p class="page-kicker">项目设置 / 本地工作区</p><h1>项目设置</h1><p>配置 API、审计参数、数据位置和工作区导出。</p></div><div class="head-actions"><span class="status-pill ready">本地优先</span></div></div><div class="settings-layout"><nav class="card settings-nav"><button class="settings-tab ${settingsTab === 'api' ? 'active' : ''}" data-settings-tab="api">${icon('spark')}研究助手 API</button><button class="settings-tab ${settingsTab === 'project' ? 'active' : ''}" data-settings-tab="project">${icon('folder')}项目参数</button><button class="settings-tab ${settingsTab === 'paths' ? 'active' : ''}" data-settings-tab="paths">${icon('database')}数据位置</button><button class="settings-tab ${settingsTab === 'backup' ? 'active' : ''}" data-settings-tab="backup">${icon('save')}备份与导出</button></nav><div class="settings-content">${settingsTab === 'api' ? renderApiSettings() : settingsTab === 'project' ? renderProjectSettings() : settingsTab === 'paths' ? renderPathSettings() : renderBackupSettings()}</div></div>`; }
  function renderApiSettings() { return `<section class="card settings-card"><h2>研究助手 API</h2><p>研究助手是可选模块，不参与确定性计算，也不会自动修改底稿结论。API Key 通过 Electron safeStorage 保存。</p><div class="form-grid"><div class="form-field full"><label>Endpoint <small>OpenAI-compatible Chat Completions</small></label><input id="api-endpoint" value="${esc(settings.endpoint || '')}" placeholder="http://127.0.0.1:11434/v1" /></div><div class="form-field"><label>API Key <small>${settings.hasApiKey ? '已安全保存' : '未设置'}</small></label><input id="api-key" type="password" placeholder="${settings.hasApiKey ? '留空表示保持现有密钥' : '可留空（本地服务）'}" /></div><div class="form-field"><label>模型</label><input id="api-model" value="${esc(settings.model || 'gpt-4o-mini')}" /></div><div class="form-field"><label>Temperature</label><input id="api-temperature" type="number" min="0" max="2" step="0.1" value="${esc(settings.temperature ?? 0.2)}" /></div><div class="form-field full"><label>系统提示词</label><textarea id="api-system">${esc(settings.systemPrompt || '')}</textarea></div></div><div class="settings-actions"><button class="btn primary" data-action="save-api">${icon('save')}保存 API 设置</button><button class="btn" data-action="open-assistant">打开研究助手</button></div><div class="notice">${icon('info')}生产环境建议使用自己的后端代理，不把生产密钥写入前端代码、导出的工作区或 Git 仓库。</div></section>`; }
  function renderProjectSettings() { const project = activeProject(); return `<section class="card settings-card"><h2>项目参数</h2><p>项目上下文会随导出的底稿和结果一起保存。</p><div class="form-grid"><div class="form-field"><label>项目名称</label><input id="project-name" value="${esc(project.name || '')}" /></div><div class="form-field"><label>客户 / 主体</label><input id="project-client" value="${esc(project.client || '')}" /></div><div class="form-field full"><label>报告期间</label><input id="project-period" value="${esc(project.period || '')}" /></div></div><div class="settings-actions"><button class="btn primary" data-action="save-project">保存项目参数</button><button class="btn" data-action="new-project">新建项目</button></div></section>`; }
  function renderPathSettings() { return `<section class="card settings-card"><h2>数据位置</h2><p>应用只保存工作区状态、字段摘要和结果，不复制原始文件。原始文件请保留在受控目录。</p><div class="path-box" id="user-data-path">${esc(appInfo?.userData || '桌面应用数据目录')}</div><div id="vendor-box" class="data-readiness" style="margin-top:12px"><div class="readiness-row"><span>内置组件</span><strong>检测中…</strong></div></div><div class="notice">${icon('shield')}建议为每个项目建立独立目录，保留原始文件、导入批次、规则版本、结果文件和复核记录。</div><div class="settings-actions"><button class="btn" data-action="open-data-folder">打开数据目录</button></div></section>`; }
  function renderBackupSettings() { return `<section class="card settings-card"><h2>备份与导出</h2><p>导出工作区 JSON、底稿索引和最近一次程序结果。导出前请确认其中没有不应共享的 API 配置。</p><div class="head-actions"><button class="btn primary" data-action="export-workspace">${icon('download')}导出工作区</button><button class="btn" data-action="export-result">${icon('file')}导出当前结果</button></div><div class="notice">${icon('info')}建议每次复核完成后导出一次。源数据、规则版本、运行时间和复核人应一并归档。</div></section>`; }

  function inspectToolData(tool) { const data = importedData; if (!data) return null; const headers = data.headers || []; const rows = data.rows || []; const readiness = toolReady(tool, data); const findings = []; const metrics = []; const tolerance = 0.01; const cutoff = new Date('2025-12-31T00:00:00');
    if (tool.id === 'cash') runCash(rows, headers, findings, metrics, tolerance);
    if (tool.id === 'revenue') runRevenue(rows, headers, findings, metrics, cutoff);
    if (tool.id === 'procurement') runProcurement(rows, headers, findings, metrics, tolerance);
    if (tool.id === 'inventory') runInventory(rows, headers, findings, metrics, tolerance);
    if (tool.id === 'expense') runExpense(rows, headers, findings, metrics, tolerance);
    if (tool.id === 'payroll') runPayroll(rows, headers, findings, metrics, tolerance);
    if (tool.id === 'journal') runJournal(rows, headers, findings, metrics, tolerance);
    metrics.unshift({ label: '总体记录', value: int(rows.length) }); metrics.push({ label: '异常项目', value: int(findings.length), level: findings.length ? 'review' : '' });
    return { toolId: tool.id, toolName: tool.name, population: rows.length, metrics, findings, readiness, createdAt: timeNow(), source: data.name };
  }
  function runCash(rows, headers, findings, metrics, tolerance) { const date = firstExisting(headers, ['日期', '交易日', 'date']); const ref = firstExisting(headers, ['流水号', '参考号', '交易号', 'reference']); const debit = firstExisting(headers, ['借方', '收入', '收款', 'debit']); const credit = firstExisting(headers, ['贷方', '支出', '付款', 'credit']); const book = firstExisting(headers, ['账面余额', '账面', 'book']); const bank = firstExisting(headers, ['银行余额', '银行', 'bank']); const seen = new Map(); let debitTotal = 0; let creditTotal = 0; rows.forEach((row, index) => { const d = numberValue(row[debit]); const c = numberValue(row[credit]); debitTotal += d; creditTotal += c; const key = normalize(rowText(row, ref)); if (key) { if (seen.has(key)) addFinding(findings, 'cash', '高', '重复流水', `第 ${index + 1} 行`, `银行流水号 ${rowText(row, ref)} 在第 ${seen.get(key) + 1} 行和第 ${index + 1} 行重复。`, rowText(row, date) || `row ${index + 1}`, '核对银行回单、记账凭证和是否存在重复入账。'); else seen.set(key, index); } if (book && bank) { const diff = numberValue(row[book]) - numberValue(row[bank]); if (Math.abs(diff) > tolerance) addFinding(findings, 'cash', '中', '余额差异', `第 ${index + 1} 行`, `账面余额与银行余额相差 ${money(diff)}。`, rowText(row, ref) || '余额字段', '补充未达账项清单并确认截止日期。'); } }); metrics.push({ label: '借方合计', value: money(debitTotal) }, { label: '贷方合计', value: money(creditTotal) }); }
  function runRevenue(rows, headers, findings, metrics, cutoff) { const invoice = firstExisting(headers, ['发票号', '发票号码', 'invoice']); const customer = firstExisting(headers, ['客户', '往来单位', 'customer']); const invoiceDate = firstExisting(headers, ['发票日期', '开票日期', 'invoice date']); const shipDate = firstExisting(headers, ['发货日期', '交付日期', '验收日期', 'ship']); const postDate = firstExisting(headers, ['入账日期', '记账日期', '确认日期', 'post']); const amount = firstExisting(headers, ['金额', '收入', '含税金额', 'amount']); const seen = new Map(); const window = 5 * 86400000; rows.forEach((row, index) => { const id = rowText(row, invoice); if (id) { const key = `${normalize(rowText(row, customer))}|${normalize(id)}|${money(numberValue(row[amount]))}`; if (seen.has(key)) addFinding(findings, 'revenue', '高', '重复收入线索', `第 ${index + 1} 行`, `客户、发票号和金额组合与第 ${seen.get(key) + 1} 行重复。`, id, '核对发票验真、红字冲销、发货和总账支持。'); else seen.set(key, index); } const dates = [rowText(row, invoiceDate), rowText(row, shipDate), rowText(row, postDate)].map(dateValue).filter(Boolean); if (dates.some((date) => Math.abs(date - cutoff) <= window)) addFinding(findings, 'revenue', '中', '截止窗口', `第 ${index + 1} 行`, `发票、发货或入账日期落在报告期末 ±5 天窗口。`, [rowText(row, invoiceDate), rowText(row, shipDate), rowText(row, postDate)].filter(Boolean).join(' / '), '取得签收、验收和期后回款证据，确认是否属于本期。'); if (!rowText(row, customer)) addFinding(findings, 'revenue', '低', '字段缺失', `第 ${index + 1} 行`, '客户或往来单位为空。', '客户字段', '补充客户主数据和合同信息。'); }); metrics.push({ label: '截止窗口', value: `${int(findings.filter((item) => item.type === '截止窗口').length)} 条` }, { label: '重复组合', value: `${int(findings.filter((item) => item.type === '重复收入线索').length)} 条` }); }
  function runProcurement(rows, headers, findings, metrics, tolerance) { const supplier = firstExisting(headers, ['供应商', 'vendor', '往来单位']); const invoice = firstExisting(headers, ['发票号', '发票号码', 'invoice']); const po = firstExisting(headers, ['订单金额', '采购金额', 'po amount']); const gr = firstExisting(headers, ['验收金额', '收货金额', 'gr amount']); const inv = firstExisting(headers, ['发票金额', 'invoice amount']); const pay = firstExisting(headers, ['付款日期', '支付日期', 'payment']); const seen = new Map(); rows.forEach((row, index) => { const poAmount = numberValue(row[po]); const grAmount = numberValue(row[gr]); const invAmount = numberValue(row[inv]); const maxDiff = Math.max(Math.abs(poAmount - grAmount), Math.abs(poAmount - invAmount), Math.abs(grAmount - invAmount)); if (maxDiff > tolerance) addFinding(findings, 'procurement', '高', '三单差异', `第 ${index + 1} 行`, `订单、验收和发票最大差异为 ${money(maxDiff)}。`, rowText(row, invoice) || rowText(row, supplier) || `row ${index + 1}`, '核对合同、验收数量、单价、税额和发票。'); const key = `${normalize(rowText(row, supplier))}|${normalize(rowText(row, invoice))}`; if (key !== '|') { if (seen.has(key)) addFinding(findings, 'procurement', '高', '重复发票', `第 ${index + 1} 行`, `供应商与发票号组合与第 ${seen.get(key) + 1} 行重复。`, rowText(row, invoice), '检查重复付款、红字发票和重复入账。'); else seen.set(key, index); } if (!rowText(row, gr)) addFinding(findings, 'procurement', '中', '缺少验收', `第 ${index + 1} 行`, '未识别到验收单号或验收金额。', rowText(row, invoice) || '采购记录', '补充验收 / 服务确认资料。'); if (pay && !rowText(row, pay)) addFinding(findings, 'procurement', '低', '付款日期缺失', `第 ${index + 1} 行`, '记录有发票但未识别到付款日期。', rowText(row, invoice) || '发票', '与应付和银行流水核对。'); }); metrics.push({ label: '三单差异', value: `${int(findings.filter((item) => item.type === '三单差异').length)} 条` }, { label: '重复发票', value: `${int(findings.filter((item) => item.type === '重复发票').length)} 条` }); }
  function runInventory(rows, headers, findings, metrics, tolerance) { const item = firstExisting(headers, ['物料', '存货', '商品', 'item']); const opening = firstExisting(headers, ['期初数量', '期初', 'opening']); const receipt = firstExisting(headers, ['入库', '收货', 'receipt']); const issue = firstExisting(headers, ['出库', '发货', 'issue']); const adjust = firstExisting(headers, ['调整', 'adjust']); const closing = firstExisting(headers, ['期末数量', '期末', 'closing']); const cost = firstExisting(headers, ['单位成本', '单价', 'cost']); const amount = firstExisting(headers, ['金额', '账面金额', 'amount']); rows.forEach((row, index) => { const expected = numberValue(row[opening]) + numberValue(row[receipt]) - numberValue(row[issue]) + numberValue(row[adjust]); const actual = numberValue(row[closing]); const diff = actual - expected; if (Math.abs(diff) > tolerance) addFinding(findings, 'inventory', '高', '数量滚动差异', `第 ${index + 1} 行`, `期初 + 入库 − 出库 ± 调整 = ${money(expected)}，与期末 ${money(actual)} 相差 ${money(diff)}。`, rowText(row, item) || `row ${index + 1}`, '核对出入库单、调整审批和盘点结果。'); if (actual < 0 || numberValue(row[cost]) < 0) addFinding(findings, 'inventory', '高', '负数项目', `第 ${index + 1} 行`, '数量或单位成本出现负数。', rowText(row, item) || '存货项目', '检查红字、调整和存货明细。'); if (actual !== 0 && numberValue(row[cost]) === 0) addFinding(findings, 'inventory', '中', '零成本项目', `第 ${index + 1} 行`, '期末有数量但单位成本为零。', rowText(row, item) || '存货项目', '核对计价政策、成本数据和结转。'); if (cost && amount) { const expectedAmount = actual * numberValue(row[cost]); const amountDiff = numberValue(row[amount]) - expectedAmount; if (Math.abs(amountDiff) > tolerance) addFinding(findings, 'inventory', '中', '估值差异', `第 ${index + 1} 行`, `数量 × 单位成本与账面金额相差 ${money(amountDiff)}。`, rowText(row, item) || '存货项目', '核对单位成本、计量单位和存货估值。'); } }); metrics.push({ label: '滚动差异', value: `${int(findings.filter((item) => item.type === '数量滚动差异').length)} 条` }, { label: '估值差异', value: `${int(findings.filter((item) => item.type === '估值差异').length)} 条` }); }
  function runExpense(rows, headers, findings, metrics, tolerance) { const employee = firstExisting(headers, ['员工', '报销人', 'employee']); const date = firstExisting(headers, ['日期', '发生日', 'date']); const vendor = firstExisting(headers, ['供应商', '商户', 'vendor']); const invoice = firstExisting(headers, ['发票号', '票据号', 'invoice']); const amount = firstExisting(headers, ['金额', '报销金额', 'amount']); const summary = firstExisting(headers, ['摘要', '事由', '说明', 'description']); const seen = new Map(); rows.forEach((row, index) => { const key = `${normalize(rowText(row, employee))}|${normalize(rowText(row, vendor))}|${normalize(rowText(row, invoice))}|${money(numberValue(row[amount]))}`; if (key.replace(/\|/g, '')) { if (seen.has(key)) addFinding(findings, 'expense', '高', '重复费用', `第 ${index + 1} 行`, `员工、供应商、发票号和金额组合与第 ${seen.get(key) + 1} 行重复。`, rowText(row, invoice) || rowText(row, vendor), '核对原图、支付回单、审批和是否重复报销。'); else seen.set(key, index); } const value = numberValue(row[amount]); if (value > 0 && value % 1000 === 0) addFinding(findings, 'expense', '低', '整数金额', `第 ${index + 1} 行`, `金额 ${money(value)} 为整千元。`, rowText(row, vendor) || rowText(row, employee), '结合合同、审批和业务背景解释。'); if (!rowText(row, summary)) addFinding(findings, 'expense', '中', '事由缺失', `第 ${index + 1} 行`, '未识别到费用摘要或业务说明。', rowText(row, employee) || '费用记录', '补充业务目的和责任说明。'); if (!rowText(row, invoice)) addFinding(findings, 'expense', '中', '发票缺失', `第 ${index + 1} 行`, '未识别到发票号或票据号。', rowText(row, vendor) || rowText(row, employee), '补充合规票据和支付证据。'); }); metrics.push({ label: '重复费用', value: `${int(findings.filter((item) => item.type === '重复费用').length)} 条` }, { label: '资料缺口', value: `${int(findings.filter((item) => item.type.includes('缺失')).length)} 条` }); }
  function runPayroll(rows, headers, findings, metrics, tolerance) { const employee = firstExisting(headers, ['员工编号', '工号', 'employee']); const name = firstExisting(headers, ['姓名', '员工姓名', 'name']); const gross = firstExisting(headers, ['应发', '工资', 'gross']); const net = firstExisting(headers, ['实发', '净工资', 'net']); const hours = firstExisting(headers, ['工时', '小时', 'hours']); const rate = firstExisting(headers, ['费率', '时薪', 'rate']); const seen = new Map(); rows.forEach((row, index) => { const key = `${normalize(rowText(row, employee))}|${normalize(rowText(row, name))}`; if (key.replace(/\|/g, '') && seen.has(key)) addFinding(findings, 'payroll', '高', '重复员工记录', `第 ${index + 1} 行`, `员工编号和姓名组合与第 ${seen.get(key) + 1} 行重复。`, rowText(row, name) || rowText(row, employee), '与人员主数据和工资发放文件核对。'); else if (key.replace(/\|/g, '')) seen.set(key, index); if (hours && rate && gross) { const calc = numberValue(row[hours]) * numberValue(row[rate]); const diff = numberValue(row[gross]) - calc; if (Math.abs(diff) > tolerance) addFinding(findings, 'payroll', '中', '应发重算差异', `第 ${index + 1} 行`, `工时 × 费率与应发相差 ${money(diff)}。`, rowText(row, name) || '工资记录', '核对考勤、费率变更和批准依据。'); } if (net && numberValue(row[net]) < 0) addFinding(findings, 'payroll', '高', '负实发', `第 ${index + 1} 行`, '实发金额为负数。', rowText(row, name) || '工资记录', '检查补扣、离职结算和付款文件。'); if (!employee) addFinding(findings, 'payroll', '中', '员工主数据缺失', `第 ${index + 1} 行`, '未识别到员工编号或工号。', rowText(row, name) || '工资记录', '补充人员主数据和入职状态。'); }); metrics.push({ label: '重复员工', value: `${int(findings.filter((item) => item.type === '重复员工记录').length)} 条` }, { label: '重算差异', value: `${int(findings.filter((item) => item.type === '应发重算差异').length)} 条` }); }
  function runJournal(rows, headers, findings, metrics, tolerance) { const voucher = firstExisting(headers, ['凭证号', '凭证编号', 'voucher']); const date = firstExisting(headers, ['日期', '记账日期', 'date']); const debit = firstExisting(headers, ['借方', 'debit']); const credit = firstExisting(headers, ['贷方', 'credit']); const summary = firstExisting(headers, ['摘要', 'description']); const source = firstExisting(headers, ['来源', 'source']); const groups = new Map(); const fingerprints = new Map(); rows.forEach((row, index) => { const id = rowText(row, voucher); if (id) { const group = groups.get(id) || { debit: 0, credit: 0 }; group.debit += numberValue(row[debit]); group.credit += numberValue(row[credit]); groups.set(id, group); } const fp = `${normalize(rowText(row, summary))}|${money(Math.max(numberValue(row[debit]), numberValue(row[credit])))}|${normalize(rowText(row, source))}`; if (fp.replace(/\|/g, '') && fingerprints.has(fp)) addFinding(findings, 'journal', '中', '重复分录指纹', `第 ${index + 1} 行`, `摘要、金额和来源组合与第 ${fingerprints.get(fp) + 1} 行重复。`, id || `row ${index + 1}`, '核对原始单据、冲销关系和总账支持。'); else if (fp.replace(/\|/g, '')) fingerprints.set(fp, index); const amount = Math.max(numberValue(row[debit]), numberValue(row[credit])); if (amount >= 100000) addFinding(findings, 'journal', '中', '大额分录', `第 ${index + 1} 行`, `分录金额 ${money(amount)} 达到当前筛查阈值 100,000。`, id || rowText(row, date), '检查合同、审批、付款和期末截止。'); if (/咨询|维修|服务|调整|冲销|备用金/.test(rowText(row, summary))) addFinding(findings, 'journal', '低', '关键词分录', `第 ${index + 1} 行`, `摘要包含需要业务解释的关键词：${rowText(row, summary)}。`, id || `row ${index + 1}`, '补充合同、验收和审批依据。'); }); groups.forEach((group, id) => { const diff = group.debit - group.credit; if (Math.abs(diff) > tolerance) addFinding(findings, 'journal', '高', '凭证不平衡', id, `借方 ${money(group.debit)}，贷方 ${money(group.credit)}，差额 ${money(diff)}。`, id, '检查分录行、科目和过账状态。'); }); metrics.push({ label: '不平衡凭证', value: `${int(findings.filter((item) => item.type === '凭证不平衡').length)} 张` }, { label: '大额分录', value: `${int(findings.filter((item) => item.type === '大额分录').length)} 条` }); }

  function formatSize(bytes) { if (!Number.isFinite(Number(bytes))) return '本地文件'; if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / (1024 * 1024)).toFixed(1)} MB`; }
  function openModal(title, subtitle, body, footer = '', options = {}) { const root = $('#modal-root'); root.innerHTML = `<div class="modal-backdrop"><section class="modal ${options.wide ? 'wide' : ''} ${options.className || ''}" role="dialog" aria-modal="true"><header class="modal-head"><div><h2>${title}</h2>${subtitle ? `<p>${subtitle}</p>` : ''}</div><button class="modal-close" data-action="close-modal">${icon('x')}</button></header><div class="modal-body">${body}</div>${footer ? `<footer class="modal-foot">${footer}</footer>` : ''}</section></div>`; hydrateIcons(root); }
  function closeModal() { $('#modal-root').innerHTML = ''; }
  function openTaskModal() { openModal('新增待办', '把审计目标拆成可执行动作。', `<div class="form-grid"><div class="form-field full"><label>事项</label><input id="new-task-title" placeholder="例如：抽查 30 笔费用报销单据" /></div><div class="form-field"><label>审计领域</label><input id="new-task-area" placeholder="费用报销" /></div><div class="form-field"><label>优先级</label><select id="new-task-priority"><option>高</option><option selected>中</option><option>低</option></select></div><div class="form-field"><label>截止时间</label><input id="new-task-due" value="本周" /></div></div>`, `<button class="btn" data-action="close-modal">取消</button><button class="btn primary" data-action="save-task">保存待办</button>`); }
  function openEvidenceModal() { openModal('新增证据 / 底稿', '登记来源和复核状态，后续可把程序结果关联到这里。', `<div class="form-grid"><div class="form-field"><label>底稿编号</label><input id="evidence-code" placeholder="A-1202" /></div><div class="form-field"><label>类型</label><select id="evidence-type"><option>分析程序</option><option>抽样测试</option><option>穿行测试</option><option>函证 / 外部证据</option><option>分析底稿</option></select></div><div class="form-field full"><label>标题</label><input id="evidence-title" placeholder="例如：存货监盘程序与差异汇总" /></div><div class="form-field full"><label>来源 / 证据位置</label><input id="evidence-source" placeholder="文件名、文件夹或链接" /></div></div>`, `<button class="btn" data-action="close-modal">取消</button><button class="btn primary" data-action="save-evidence">保存证据</button>`); }
  function openGuideModal() { openModal('AuditDesk 工作标准', '用确定性检查产生线索，用证据和人工判断完成审计结论。', `<div class="markdown"><h2>标准工作流</h2><ol><li>确认项目、主体、期间、币种和重要性。</li><li>导入原始数据，保留文件和处理记录。</li><li>确认总体完整性、字段口径和缺失值。</li><li>运行程序，逐条复核异常和源记录。</li><li>登记证据、解释、调整和复核状态。</li><li>导出底稿索引、问题清单和复核摘要。</li></ol><h2>不做的事情</h2><ul><li>不把异常分数直接定性为舞弊。</li><li>不在缺少总体时给出“通过”结论。</li><li>不覆盖已接受的导入批次和底稿版本。</li></ul></div>`, `<button class="btn primary" data-action="close-modal">知道了</button>`, { wide: true }); }
  function openSampleMenu() { openModal('载入模块示例', '示例数据仅用于熟悉字段和规则，不代表真实客户数据。', `<div class="tool-grid">${toolCatalog.map((tool) => `<button class="tool-card" data-sample-tool="${tool.id}"><div class="tool-card-head"><span class="tool-card-icon">${icon(tool.icon)}</span><span class="status-pill ready">可载入</span></div><h3>${tool.name}</h3><p>${tool.short}</p><div class="tool-card-foot"><span>${tool.code}</span><span>示例 CSV</span></div></button>`).join('')}</div>`, `<button class="btn" data-action="close-modal">取消</button>`, { wide: true }); }
  function openAssistant() { const messages = assistantHistory.length ? assistantHistory.map((message) => `<div class="chat-message ${message.role === 'user' ? 'user' : 'ai'}"><span class="chat-avatar">${message.role === 'user' ? '我' : icon('spark')}</span><div class="chat-bubble">${formatChat(message.content)}</div></div>`).join('') : '<div class="chat-message ai"><span class="chat-avatar">研</span><div class="chat-bubble">可以问我如何设计程序、如何解释异常，或如何把发现整理成底稿。回答仅作研究辅助。</div></div>'; openModal('研究助手', settings.endpoint ? '已连接配置的研究服务' : '尚未配置 API，可在项目设置中填写', `<div class="assistant-body"><div class="assistant-messages" id="assistant-messages">${messages}</div><div class="chat-compose"><textarea id="assistant-input" placeholder="输入问题…"></textarea><button class="btn primary" data-action="send-assistant" id="assistant-send">发送</button></div></div>`, `<button class="btn" data-action="close-modal">关闭</button><button class="btn ghost" data-action="open-settings-from-assistant">API 设置</button>`, { className: 'assistant-modal' }); }
  function openSqlModal() { if (!importedData) { toast('请先导入数据。', 'info'); return; } openModal('SQL 工作台', '使用内置 DuckDB 查询当前数据。结果只读，不修改源文件。', `<div class="form-field"><label>SQL 查询</label><textarea id="sql-input" rows="9" style="font-family:Consolas,monospace">SELECT * FROM audit_input LIMIT 20;</textarea><span class="form-hint">当前数据以临时视图 <code>audit_input</code> 载入。可使用标准 DuckDB SQL。</span></div><div id="sql-result"></div>`, `<button class="btn" data-action="close-modal">关闭</button><button class="btn primary" data-action="run-sql">${icon('play')}运行查询</button>`, { wide: true }); }
  async function runSql() { const sql = $('#sql-input')?.value.trim(); if (!sql || !bridge) return; const resultBox = $('#sql-result'); if (resultBox) resultBox.innerHTML = '<div class="notice">正在执行…</div>'; try { const result = await bridge.queryDuckDb({ sql, headers: importedData.headers, rows: importedData.rows, sourcePath: importedData.path }); const records = JSON.parse(result.stdout || '[]'); const preview = records.slice(0, 30); const headers = preview.length ? Object.keys(preview[0]) : []; if (resultBox) resultBox.innerHTML = `<div class="section-title"><h2>查询结果</h2><span>${int(preview.length)} 行预览 · ${int(result.elapsedMs)} ms</span></div><div class="table-wrap"><table class="data-table"><thead><tr>${headers.map((header) => `<th>${esc(header)}</th>`).join('')}</tr></thead><tbody>${preview.map((row) => `<tr>${headers.map((header) => `<td>${esc(row[header] ?? '—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; } catch (error) { if (resultBox) resultBox.innerHTML = `<div class="notice">${icon('alert')}${esc(error.message)}</div>`; } }
  function formatChat(text) { return esc(text).replace(/\n/g, '<br>').replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>'); }
  async function sendAssistant() { const input = $('#assistant-input'); const text = input?.value.trim(); if (!text || assistantBusy) return; if (!settings.endpoint) { toast('请先在项目设置中配置研究助手 Endpoint。', 'info'); return; } assistantHistory.push({ role: 'user', content: text }); input.value = ''; assistantBusy = true; const messages = $('#assistant-messages'); if (messages) messages.insertAdjacentHTML('beforeend', '<div class="chat-message ai"><span class="chat-avatar">研</span><div class="chat-bubble">正在整理…</div></div>'); try { const system = `${settings.systemPrompt}\n\n当前项目：${activeProject().name || ''}；期间：${activeProject().period || ''}。只提供研究辅助，不把回答当成审计结论。`; const answer = await bridge.askApi({ endpoint: settings.endpoint, model: settings.model, temperature: settings.temperature, messages: [{ role: 'system', content: system }, ...assistantHistory.map((message) => ({ role: message.role, content: message.content }))] }); assistantHistory.push({ role: 'assistant', content: answer }); } catch (error) { assistantHistory.push({ role: 'assistant', content: `请求未完成：${error.message}` }); } finally { assistantBusy = false; openAssistant(); } }

  async function openFile() { if (!bridge) { toast('文件选择仅在桌面应用中可用。', 'info'); return; } try { const result = await bridge.openDataFile(); if (!result) return; if (result.kind === 'table') { importedData = result; toolResult = null; currentView = 'data'; render(); toast(`已载入 ${result.name}`, 'success'); } else { const canExtract = result.kind === 'pdf' || result.kind === 'image'; openModal('文档资料', canExtract ? '可提取文本或 OCR，再将结果作为证据登记。' : '该文件类型暂不进入自动处理。', `<div class="path-box">${esc(result.path || result.name)}</div><div id="document-result" class="notice">${icon('info')}${canExtract ? '尚未提取文本。' : '请作为证据文件登记。'}</div>${canExtract ? `<pre id="document-text" style="max-height:220px;overflow:auto;padding:10px;border:1px solid #e2e9ee;border-radius:5px;background:#fafbfc;color:#5b6d7e;font:9px/1.6 Consolas,monospace;white-space:pre-wrap"></pre>` : ''}`, `${canExtract ? `<button class="btn primary" data-action="extract-document" data-path="${esc(result.path)}">${icon('play')}提取文本 / OCR</button>` : ''}<button class="btn" data-action="close-modal">关闭</button>`, { wide: true }); } } catch (error) { toast(`读取失败：${error.message}`, 'error'); } }
  async function extractDocument(filePath) { const output = $('#document-text'); const resultBox = $('#document-result'); if (resultBox) resultBox.innerHTML = `${icon('info')}正在提取，请稍候…`; try { const result = await bridge.extractDocument(filePath); if (output) output.textContent = result.text || '未识别到文本'; if (resultBox) resultBox.innerHTML = `${icon('check-circle')}已提取 ${result.pages ? `${result.pages} 页` : '图片'}，请人工核对金额、日期和页码。`; } catch (error) { if (resultBox) resultBox.innerHTML = `${icon('alert')}${esc(error.message)}`; } }
  function loadToolSample() { const tool = currentTool() || toolCatalog.find((item) => item.id === 'cash'); const sample = sampleData[tool.id]; if (!sample) return; importedData = { ...clone(sample), kind: 'table', size: 12000, format: 'CSV' }; activeToolId = tool.id; currentView = 'procedures'; toolResult = null; render(); toast(`已载入 ${tool.name} 示例数据`, 'success'); }
  function runCurrentTool() { const tool = currentTool(); if (!tool) return; if (!importedData) { toast('请先导入数据或载入样例。', 'info'); return; } toolResult = inspectToolData(tool); render(); toast(`${tool.name} 已完成 ${int(toolResult.findings.length)} 条待复核线索`, toolResult.findings.length ? 'info' : 'success'); }
  function saveIssue(findingId) { if (!toolResult) return; const finding = toolResult.findings.find((item) => item.id === findingId); if (!finding) return; const item = { id: uid('e'), code: `E-${String(workspace.evidence.length + 1).padStart(4, '0')}`, title: finding.type, type: '程序异常', status: '待复核', source: `${toolResult.toolName} · ${toolResult.source}`, updatedAt: timeNow() }; workspace.evidence.unshift(item); saveWorkspace(); render(); toast('已登记到底稿与证据。', 'success'); }
  function addNote() { const input = $('#evidence-note'); const text = input?.value.trim(); if (!text) { toast('请输入笔记内容。', 'info'); return; } workspace.notes.unshift({ id: uid('n'), text, time: timeNow() }); saveWorkspace(); input.value = ''; render(); toast('笔记已保存。', 'success'); }
  function toggleTask(id) { const task = (workspace.tasks || []).find((item) => item.id === id); if (!task) return; task.done = !task.done; saveWorkspace(); render(); }
  function addTask() { const title = $('#new-task-title')?.value.trim(); if (!title) { toast('请填写事项。', 'info'); return; } workspace.tasks.unshift({ id: uid('t'), title, area: $('#new-task-area')?.value.trim() || '未分类', priority: $('#new-task-priority')?.value || '中', due: $('#new-task-due')?.value.trim() || '待安排', done: false }); saveWorkspace(); closeModal(); render(); toast('待办已新增。', 'success'); }
  function addEvidence() { const title = $('#evidence-title')?.value.trim(); if (!title) { toast('请填写证据标题。', 'info'); return; } workspace.evidence.unshift({ id: uid('e'), code: $('#evidence-code')?.value.trim() || `A-${String(workspace.evidence.length + 1).padStart(4, '0')}`, title, type: $('#evidence-type')?.value || '分析程序', status: '草稿', source: $('#evidence-source')?.value.trim() || '待补充', updatedAt: timeNow() }); saveWorkspace(); closeModal(); render(); toast('证据索引已新增。', 'success'); }
  async function saveApiSettings() { const next = { endpoint: $('#api-endpoint')?.value.trim() || '', model: $('#api-model')?.value.trim() || 'gpt-4o-mini', temperature: Number($('#api-temperature')?.value || .2), systemPrompt: $('#api-system')?.value || '' }; const key = $('#api-key')?.value; if (key) next.apiKey = key; settings = bridge ? await bridge.writeSettings(next) : { ...settings, ...next, hasApiKey: Boolean(key) }; render(); toast('API 设置已保存。', 'success'); }
  async function saveProjectSettings() { const project = activeProject(); project.name = $('#project-name')?.value.trim() || project.name; project.client = $('#project-client')?.value.trim() || project.client; project.period = $('#project-period')?.value.trim() || project.period; project.updatedAt = timeNow(); saveWorkspace(); render(); toast('项目参数已保存。', 'success'); }
  async function exportWorkspace() { if (!bridge) { toast('桌面应用中才可导出文件。', 'info'); return; } const content = JSON.stringify({ exportedAt: new Date().toISOString(), app: 'AuditDesk', workspace }, null, 2); const path = await bridge.saveFile({ defaultName: `auditdesk-workspace-${new Date().toISOString().slice(0, 10)}.json`, content }); if (path) toast('工作区已导出。', 'success'); }
  async function exportResult() { if (!toolResult) { toast('请先运行一个程序。', 'info'); return; } if (!bridge) { toast('桌面应用中才可导出文件。', 'info'); return; } const content = JSON.stringify(toolResult, null, 2); const path = await bridge.saveFile({ defaultName: `auditdesk-${toolResult.toolId}-result.json`, content }); if (path) toast('程序结果已导出。', 'success'); }
  async function exportSource() { if (!importedData || !bridge) return; const content = JSON.stringify({ file: importedData.name, headers: importedData.headers, rows: importedData.rows?.slice(0, 1000), exportedAt: new Date().toISOString() }, null, 2); const path = await bridge.saveFile({ defaultName: `auditdesk-source-summary.json`, content }); if (path) toast('源数据摘要已导出。', 'success'); }
  function go(view) { currentView = view; activeToolId = null; if (view !== 'knowledge') activeKnowledge = null; render(); }
  function openKnowledgeFile(relative) { activeKnowledge = relative; render(); const doc = $('#knowledge-content'); if (doc && bridge) bridge.readKnowledge(relative).then((result) => { doc.innerHTML = `<h1>${esc(result.name.replace(/\.(md|html|txt)$/i, ''))}</h1><p class="doc-meta">本地资料 · ${formatSize(result.content.length)}</p>${markdown(result.content)}`; }).catch((error) => { doc.innerHTML = `<div class="empty-state"><h3>读取失败</h3><p>${esc(error.message)}</p></div>`; }); }
  function markdown(text) { const lines = String(text).replace(/\r/g, '').split('\n'); let html = ''; let list = null; const closeList = () => { if (list) { html += `</${list}>`; list = null; } }; lines.forEach((line) => { const trimmed = line.trim(); if (!trimmed) { closeList(); return; } if (/^###\s+/.test(trimmed)) { closeList(); html += `<h3>${esc(trimmed.replace(/^###\s+/, ''))}</h3>`; return; } if (/^##\s+/.test(trimmed)) { closeList(); html += `<h2>${esc(trimmed.replace(/^##\s+/, ''))}</h2>`; return; } if (/^#\s+/.test(trimmed)) { closeList(); html += `<h1>${esc(trimmed.replace(/^#\s+/, ''))}</h1>`; return; } if (/^[-*]\s+/.test(trimmed)) { if (list !== 'ul') { closeList(); list = 'ul'; html += '<ul>'; } html += `<li>${inlineMarkdown(trimmed.replace(/^[-*]\s+/, ''))}</li>`; return; } if (/^\d+\.\s+/.test(trimmed)) { if (list !== 'ol') { closeList(); list = 'ol'; html += '<ol>'; } html += `<li>${inlineMarkdown(trimmed.replace(/^\d+\.\s+/, ''))}</li>`; return; } if (/^>\s?/.test(trimmed)) { closeList(); html += `<blockquote>${inlineMarkdown(trimmed.replace(/^>\s?/, ''))}</blockquote>`; return; } closeList(); html += `<p>${inlineMarkdown(trimmed)}</p>`; }); closeList(); return html; }
  function inlineMarkdown(text) { return esc(text).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/`([^`]+)`/g, '<code>$1</code>'); }

  function bindShell() { $('#import-top')?.addEventListener('click', () => openFile()); $('#save-top')?.addEventListener('click', () => saveNow()); $('#assistant-trigger')?.addEventListener('click', () => openAssistant()); $('#mobile-menu')?.addEventListener('click', () => $('#sidebar')?.classList.toggle('open')); $('#workspace-select')?.addEventListener('click', () => openProjectModal()); document.addEventListener('click', handleClick); document.addEventListener('input', handleInput); document.addEventListener('keydown', handleKeyDown); }
  function parseCsvText(text) { const source = text.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n').replace(/\r/g, '\n'); const delimiter = (source.split('\n')[0].match(/\t/g) || []).length > (source.split('\n')[0].match(/,/g) || []).length ? '\t' : ','; const records = []; let record = []; let cell = ''; let quoted = false; for (let index = 0; index < source.length; index += 1) { const char = source[index]; const next = source[index + 1]; if (char === '"' && quoted && next === '"') { cell += '"'; index += 1; continue; } if (char === '"') { quoted = !quoted; continue; } if (char === delimiter && !quoted) { record.push(cell.trim()); cell = ''; continue; } if (char === '\n' && !quoted) { record.push(cell.trim()); if (record.some((value) => value !== '')) records.push(record); record = []; cell = ''; continue; } cell += char; } if (cell.length || record.length) { record.push(cell.trim()); if (record.some((value) => value !== '')) records.push(record); } if (!records.length) throw new Error('文件中没有可读取的数据'); const headers = [...new Set(records[0].map((header, index) => header || `列${index + 1}`))]; const rows = records.slice(1, 200001).map((values) => Object.fromEntries(headers.map((header, index) => [header, values[index] || '']))); return { headers, rows, delimiter: delimiter === '\t' ? 'TSV' : 'CSV' }; }
  function handleInput(event) { if (event.target.id === 'knowledge-search') { knowledgeSearch = event.target.value; render(); const input = $('#knowledge-search'); if (input) { input.focus(); input.setSelectionRange(input.value.length, input.value.length); } } }
  function handleKeyDown(event) { if (event.key === 'Escape') closeModal(); if (event.target.id === 'assistant-input' && event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); sendAssistant(); } }
  function handleClick(event) { const view = event.target.closest('[data-view]'); if (view) { go(view.dataset.view); return; } const tool = event.target.closest('[data-tool]'); if (tool) { activeToolId = tool.dataset.tool; currentView = 'procedures'; render(); return; } const knowledge = event.target.closest('[data-knowledge]'); if (knowledge) { openKnowledgeFile(knowledge.dataset.knowledge); return; } const setting = event.target.closest('[data-settings-tab]'); if (setting) { settingsTab = setting.dataset.settingsTab; render(); return; } const sample = event.target.closest('[data-sample-tool]'); if (sample) { closeModal(); activeToolId = sample.dataset.sampleTool; currentView = 'procedures'; importedData = { ...clone(sampleData[activeToolId]), kind: 'table', size: 12000, format: 'CSV' }; toolResult = null; render(); return; } const action = event.target.closest('[data-action]'); if (!action) return; const name = action.dataset.action; if (name === 'switch-project') switchProject(action.dataset.project); else if (name === 'create-project') createProjectFromModal(); else if (name === 'open-file') openFile(); else if (name === 'load-sample-menu') openSampleMenu(); else if (name === 'load-tool-sample') loadToolSample(); else if (name === 'run-tool') runCurrentTool(); else if (name === 'back-procedures') { activeToolId = null; currentView = 'procedures'; render(); } else if (name === 'open-procedures') go('procedures'); else if (name === 'open-guide') openGuideModal(); else if (name === 'new-task') openTaskModal(); else if (name === 'save-task') addTask(); else if (name === 'toggle-task') toggleTask(action.dataset.task); else if (name === 'remove-data') { importedData = null; toolResult = null; render(); } else if (name === 'add-evidence') openEvidenceModal(); else if (name === 'save-evidence') addEvidence(); else if (name === 'add-note') addNote(); else if (name === 'save-issue') saveIssue(action.dataset.finding); else if (name === 'export-workspace') exportWorkspace(); else if (name === 'export-result') exportResult(); else if (name === 'export-source') exportSource(); else if (name === 'save-api') saveApiSettings(); else if (name === 'open-assistant') openAssistant(); else if (name === 'open-settings-from-assistant') { closeModal(); settingsTab = 'api'; go('settings'); } else if (name === 'send-assistant') sendAssistant(); else if (name === 'open-sql') openSqlModal(); else if (name === 'run-sql') runSql(); else if (name === 'save-project') saveProjectSettings(); else if (name === 'new-project') newProject(); else if (name === 'open-external') bridge?.openExternal(action.dataset.url); else if (name === 'open-data-folder') { if (appInfo?.userData) bridge?.openPath(appInfo.userData); } else if (name === 'extract-document') extractDocument(action.dataset.path); else if (name === 'close-modal') closeModal(); else if (name === 'view-last-result') { if (toolResult) { activeToolId = toolResult.toolId; currentView = 'procedures'; render(); } } }
  function newProject() { openProjectModal(); }
  function openProjectModal() { const projects = workspace.projects || []; openModal('切换项目', '选择当前工作项目，或新建一个项目。', `<div class="project-list">${projects.map((item) => `<div class="project-row"><div><strong>${esc(item.name)}</strong><span>${esc(item.client || '未设置')} · ${esc(item.period || '未设置期间')}</span></div>${item.id === workspace.activeProjectId ? '<span class="status-pill ready">当前</span>' : `<button class="btn small" data-action="switch-project" data-project="${item.id}">切换</button>`}</div>`).join('') || '<div class="empty-state">暂无项目</div>'}</div><div class="form-grid" style="margin-top:14px"><div class="form-field full"><label>新项目名称</label><input id="new-project-name" placeholder="例如：2025 年度财务报表审计" /></div><div class="form-field"><label>客户 / 主体</label><input id="new-project-client" placeholder="客户名称" /></div><div class="form-field"><label>报告期间</label><input id="new-project-period" placeholder="2025 年度" /></div></div>`, `<button class="btn" data-action="close-modal">关闭</button><button class="btn primary" data-action="create-project">新建并切换</button>`, { wide: true }); }
  function switchProject(id) { if (!(workspace.projects || []).some((item) => item.id === id)) return; workspace.activeProjectId = id; saveWorkspace(); closeModal(); render(); toast('已切换项目。', 'success'); }
  function createProjectFromModal() { const name = $('#new-project-name')?.value.trim(); if (!name) { toast('请填写项目名称。', 'info'); return; } const item = { id: uid('p'), name, client: $('#new-project-client')?.value.trim() || '待设置', period: $('#new-project-period')?.value.trim() || '待设置', status: '进行中', updatedAt: timeNow(), areas: [] }; workspace.projects.push(item); workspace.activeProjectId = item.id; saveWorkspace(); closeModal(); render(); toast('项目已创建。', 'success'); }

  init();
})();
